"""Compact import surface for schematic and diagnostic stripboard scripts."""

LOGGING_FORMAT = "%(asctime)s - %(name)-60s - %(levelname)-8s - %(message)s"


def _setup_logging():
    import os
    import sys

    def is_running_under_pytest():
        return bool(os.getenv("PYTEST_VERSION")) or "pytest" in sys.modules

    if (
        os.environ.get("MEGE_CIRCUITS_NO_LOGGING_INIT", False)
        or is_running_under_pytest()
    ):
        return

    import logging

    level = os.environ.get("MEGE_CIRCUITS_LOG_LEVEL", "INFO")
    logging.basicConfig(level=level, format=LOGGING_FORMAT, force=True)
    logging.getLogger().handlers[0].stream = sys.stdout
    package_level = logging.getLevelName(str(level).upper())
    if not isinstance(package_level, int):
        package_level = logging.INFO
    logging.getLogger("mege_circuits").setLevel(package_level)


_setup_logging()

from mege_circuits.circuit import (
    Circuit,
    Component,
    ERCIssue,
    ERCReport,
    Terminal,
    check_schema_erc,
    circuit_from_schema,
    export_netlist,
)
from mege_circuits.dsl import (
    DEFAULT_KIND_COLOR_MAP,
    DEFAULT_NET_KIND,
    Alignment,
    BjtNpn,
    BjtPnp,
    Capacitor,
    Diode,
    Direction,
    Dot,
    DualOptocoupler,
    Fuse,
    Ground,
    HexOpenCollectorBuffer,
    PMos,
    Resistor,
    SchemaNetVisualization,
    SchemaTerminalVisualization,
    Stripboard,
    StripboardBlocker,
    StripboardCut,
    StripboardLocalPoint,
    StripboardNetAssignment,
    StripboardNetRun,
    Wire,
    Zener,
    align,
    align_translation,
    assign_schema_nets_to_stripboard,
    compact_sparse_stripboard_tracks,
    compact_stripboard_connections_left,
    create_element,
    create_net,
    create_node,
    create_rail,
    create_schema,
    create_stripboard,
    create_wire,
    get_schema_net_visualizations,
    kind_color,
    modify_label_alignment,
    net_color,
    permute_stripboard_tracks_for_element_span,
    point_at,
    render_schemdraw,
    render_stripboard,
    render_stripboard_overlay,
    rotate,
    snap_schema_to_stripboard,
    translate,
)
from mege_circuits.physical import (
    Footprint,
    Jumper,
    PhysicalConductor,
    PhysicalIssue,
    PhysicalLayout,
    PhysicalNetlist,
    PhysicalVerificationReport,
    PlacedComponent,
    PlacedConnector,
    PlacedPin,
    StripboardBuildOutputs,
    StripboardRoutingHints,
    create_manual_stripboard_layout,
    default_footprints,
    extract_physical_netlist,
    footprint_for_component,
    placed_component_pins,
    plan_stripboard,
    render_stripboard_bottom,
    render_stripboard_debug,
    render_stripboard_layout,
    render_stripboard_layout_print_pdf,
    score_stripboard_layout,
    stripboard_hints_from_schema,
    verify_stripboard_layout,
    write_stripboard_build_checklist,
    write_stripboard_build_json,
    write_stripboard_build_outputs,
)
from mege_circuits.pinout import (
    DiscreteComponentPlacement,
    DiscretePinGroup,
    DiscreteViewConfig,
    PinoutBox,
    PinoutProject,
    analyze_all_connections,
    analyze_connection_violations,
    find_optimal_waypoint,
    generate_discrete_top_svg,
    generate_routed_svg,
    load_pinout_config,
    route_problematic_connections,
    write_svg,
)
from mege_circuits.stripboard import (
    StripboardLayoutProject,
    circuit_fingerprint,
    load_stripboard_layout_config,
    render_stripboard_layout_config,
    stripboard_layout_yaml_data,
    write_stripboard_layout_yaml,
)

__all__ = [
    "Alignment",
    "BjtNpn",
    "BjtPnp",
    "Capacitor",
    "Circuit",
    "Component",
    "DEFAULT_KIND_COLOR_MAP",
    "DEFAULT_NET_KIND",
    "Diode",
    "Direction",
    "DiscreteComponentPlacement",
    "DiscretePinGroup",
    "DiscreteViewConfig",
    "Dot",
    "DualOptocoupler",
    "ERCIssue",
    "ERCReport",
    "Footprint",
    "Fuse",
    "Ground",
    "HexOpenCollectorBuffer",
    "Jumper",
    "LOGGING_FORMAT",
    "PMos",
    "PhysicalConductor",
    "PhysicalIssue",
    "PhysicalLayout",
    "PhysicalNetlist",
    "PhysicalVerificationReport",
    "PlacedComponent",
    "PlacedConnector",
    "PlacedPin",
    "PinoutProject",
    "PinoutBox",
    "Resistor",
    "SchemaNetVisualization",
    "SchemaTerminalVisualization",
    "Stripboard",
    "StripboardBuildOutputs",
    "StripboardBlocker",
    "StripboardCut",
    "StripboardLayoutProject",
    "StripboardLocalPoint",
    "StripboardNetAssignment",
    "StripboardNetRun",
    "StripboardRoutingHints",
    "Terminal",
    "Wire",
    "Zener",
    "align",
    "align_translation",
    "analyze_all_connections",
    "analyze_connection_violations",
    "assign_schema_nets_to_stripboard",
    "check_schema_erc",
    "circuit_from_schema",
    "circuit_fingerprint",
    "compact_sparse_stripboard_tracks",
    "compact_stripboard_connections_left",
    "create_element",
    "create_manual_stripboard_layout",
    "create_net",
    "create_node",
    "create_rail",
    "create_schema",
    "create_stripboard",
    "create_wire",
    "default_footprints",
    "extract_physical_netlist",
    "export_netlist",
    "find_optimal_waypoint",
    "footprint_for_component",
    "generate_discrete_top_svg",
    "generate_routed_svg",
    "get_schema_net_visualizations",
    "kind_color",
    "load_pinout_config",
    "load_stripboard_layout_config",
    "modify_label_alignment",
    "net_color",
    "plan_stripboard",
    "placed_component_pins",
    "point_at",
    "permute_stripboard_tracks_for_element_span",
    "render_schemdraw",
    "render_stripboard",
    "render_stripboard_bottom",
    "render_stripboard_debug",
    "render_stripboard_layout",
    "render_stripboard_layout_config",
    "render_stripboard_layout_print_pdf",
    "render_stripboard_overlay",
    "route_problematic_connections",
    "rotate",
    "score_stripboard_layout",
    "snap_schema_to_stripboard",
    "stripboard_hints_from_schema",
    "stripboard_layout_yaml_data",
    "translate",
    "verify_stripboard_layout",
    "write_stripboard_build_checklist",
    "write_stripboard_build_json",
    "write_stripboard_build_outputs",
    "write_stripboard_layout_yaml",
    "write_svg",
]
